ALTER TABLE water_supply_form
ALTER COLUMN mark_y1 TYPE FLOAT USING mark_y1::FLOAT,
ALTER COLUMN mark_y2 TYPE FLOAT USING mark_y2::FLOAT,
ALTER COLUMN wat_vol_y1 TYPE FLOAT USING wat_vol_y1::FLOAT,
ALTER COLUMN wat_vol_y2 TYPE FLOAT USING wat_vol_y2::FLOAT;