create table if not exists gazsu_modules
(
    id          bigint generated by default as identity,
    module      varchar(255) not null
    primary key,
    name_kz     varchar(255),
    name_ru     varchar(255),
    describtion varchar(255),
    url         varchar(255)
    );

