INSERT INTO public.status (id, name_kz, name_ru, name_tech)
VALUES (1, 'В работе', 'В работе', 'puv_in_work');

INSERT INTO public.status (id, name_kz, name_ru, name_tech)
VALUES (2, 'Согласовано', 'Согласовано', 'puv_agreed');

INSERT INTO public.status (id, name_kz, name_ru, name_tech)
VALUES (3, 'На доработке', 'На доработке', 'puv_on_completetion');

INSERT INTO public.status (id, name_kz, name_ru, name_tech)
VALUES (4, 'Отозван', 'Отозван', 'puv_send_back');

INSERT INTO public.status (id, name_kz, name_ru, name_tech)
VALUES (5, 'Отправлено', 'Отправлено', 'puv_send_to');

DROP TABLE IF EXISTS report_puv;

CREATE TABLE report_puv (
                            id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            full_name              VARCHAR,
                            address                VARCHAR,
                            bin                    VARCHAR,
                            iin                    VARCHAR,
                            requisite              VARCHAR,
                            device_brand           VARCHAR,
                            last_verification_date DATE,
                            created_date           DATE,
                            create_by              VARCHAR,
                            deleted_date           DATE,
                            deleted_by             VARCHAR,
                            quarter                BIGINT,
                            quarter_date           DATE,
                            status_id              INTEGER,
                            CONSTRAINT fk_status FOREIGN KEY (status_id) REFERENCES status(id)
);
