CREATE TABLE IF NOT EXISTS channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    name VARCHAR(255),
    throughput BIGINT,
    length VARCHAR(255),
    from_zemlyan VARCHAR(255),
    from_oblicov VARCHAR(255),
    area_regular VARCHAR(255),
    kpd_project VARCHAR(255),
    kpd_fact VARCHAR(255),
    CONSTRAINT fk_organization FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE SET NULL
);