create table auth_role
(
    role      varchar(255) not null
        primary key,
    has_level varchar(255),
    is_active varchar(255),
    name_kz   varchar(255),
    name_ru   varchar(255),
    role_type varchar(255)
);

create table auth_user_recovery_tokens
(
    id             bigint not null
        primary key,
    create_date    timestamp,
    recovery_token varchar(255)
);


create table auth_user
(
    id                 bigint       not null
        primary key,
    bin                varchar(255),
    create_date        timestamp,
    email              varchar(255),
    iin                varchar(255),
    is_active          varchar(255),
    is_archive         varchar(255),
    is_deleted         boolean,
    is_director        varchar(255),
    is_root            varchar(255),
    name               varchar(255),
    order_file         bytea,
    password           varchar(255),
    patronymic         varchar(255),
    phone_number       varchar(255),
    surname            varchar(255),
    update_date        timestamp,
    deactivated_reason varchar(255),
    first_entry        varchar(255) not null,
    is_deactivated     boolean
);

create table auth_action_log
(
    id               bigint not null
        primary key,
    action           varchar(255),
    create_date      timestamp,
    last_update_date timestamp,
    name             varchar(255),
    role_id          varchar(255),
    user_id          bigint,
    create_by        bigint
        constraint fkkltosoxm2muutjx3hxx1g85wg
            references auth_user,
    last_update_by   bigint
        constraint fkist5ki0651qocmrj5nh8u4xhf
            references auth_user
);




create table auth_user_role
(
    role    varchar(255) not null
        constraint fkm1wuiwrpf6ckmfqnk56jkwash
            references auth_role,
    user_id bigint       not null
        constraint fkebutsbqm58ehnlffb299ng0ap
            references auth_user,
    primary key (user_id, role)
);

create table notification_template
(
    id               bigint generated by default as identity
        primary key,
    created          timestamp not null,
    created_user_id  bigint,
    is_deleted       boolean,
    modified         timestamp not null,
    modified_user_id bigint,
    code             varchar(255),
    message_kz       varchar(255),
    message_ru       varchar(255),
    subject_kz       varchar(255),
    subject_ru       varchar(255),
    type             varchar(255)
);

create table old_passwords
(
    id          bigint not null
        primary key,
    create_date timestamp,
    hash        varchar(255),
    iin         varchar(255)
);

create table roles
(
    id               bigint generated by default as identity
        primary key,
    created          timestamp not null,
    created_user_id  bigint,
    is_deleted       boolean,
    modified         timestamp not null,
    modified_user_id bigint,
    code             varchar(255),
    name             varchar(255)
);


create sequence ses_id_seq;


create table ses
(
    id       bigint default nextval('ses_id_seq'::regclass) not null
        primary key,
    active   boolean,
    bin      varchar(255),
    dat      timestamp,
    exp_date timestamp,
    iin      varchar(255),
    ip       varchar(255),
    token    varchar,
    user_id  bigint
);

create table status
(
    id        bigint not null
        primary key,
    name_kz   varchar(255),
    name_ru   varchar(255),
    name_tech varchar(255)
);

create table auth_action_role
(
    id              bigint not null
        primary key,
    is_active       varchar(255),
    role            varchar(255)
        constraint fk8jgytoixms3yrfw32torx3kso
            references auth_role,
    status_id       bigint
        constraint fketfv0s0ns4a16tf5uqdnqb7uk
            references status
);

create table user_passwords_info
(
    iin                 varchar(255) not null
        primary key,
    last_changed_date   timestamp,
    last_login_date     timestamp,
    valid_login_count   bigint,
    wrong_attempt_count bigint
);


create table user_roles
(
    id               bigint generated by default as identity
        primary key,
    created          timestamp not null,
    created_user_id  bigint,
    is_deleted       boolean,
    modified         timestamp not null,
    modified_user_id bigint,
    role_id          bigint,
    user_id          bigint
);


create table user_session
(
    id          bigint not null
        primary key,
    action      varchar(255),
    active      boolean,
    create_date timestamp,
    details     varchar(255),
    exp_date    timestamp,
    iin         varchar(255),
    ip          varchar(255),
    token       varchar(255)
);


create sequence auth_action_log_id_seq;


create sequence auth_users_s;

create sequence old_passwords_s;

create sequence user_session_s;

create sequence user_session_gen
    increment by 50;
