create table auth_action
(
    action    varchar(255) not null
        primary key,
    is_active varchar(255),
    module    varchar(255),
    name_kz   varchar(255),
    name_ru   varchar(255)
);

create table auth_dict
(
    id           bigint not null
        primary key,
    dict_type    varchar(255),
    is_active    varchar(255),
    name_kz      varchar(255),
    name_ru      varchar(255),
    order_number bigint,
    schema_name  varchar(255),
    table_name   varchar(255)
);

create table auth_level
(
    lev          varchar(255) not null
        primary key,
    name_kz      varchar(255),
    name_ru      varchar(255),
    order_number double precision
);


create table auth_module
(
    module            varchar(255) not null
        primary key,
    name_kz           varchar(255),
    name_ru           varchar(255),
    order_number      double precision,
    project_name      varchar(255),
    show_registration varchar(255),
    url               varchar(255)
);

create table auth_module_level
(
    id     bigint not null
        primary key,
    lev    varchar(255)
        constraint fk9w48okdcetkwepvjw95pnhw3d
            references auth_level,
    module varchar(255)
        constraint fkjhtmud0jvf2qbivatkkk7u0um
            references auth_module
);


create table auth_role
(
    role      varchar(255) not null
        primary key,
    has_level varchar(255),
    is_active varchar(255),
    module    varchar(255)
        constraint fkbikaits4v1tu2jtn2rn0dks1i
            references auth_module,
    name_kz   varchar(255),
    name_ru   varchar(255),
    role_type varchar(255)
);

create table auth_user_recovery_tokens
(
    id             bigint not null
        primary key,
    create_date    timestamp,
    recovery_token varchar(255)
);


create table legal_entity
(
    id           bigint generated by default as identity
        primary key,
    bin          varchar(255) not null,
    created_date timestamp,
    name_kz      varchar(255),
    name_ru      varchar(255),
    updated_date timestamp
);

create table auth_user
(
    id                 bigint       not null
        primary key,
    bin                varchar(255),
    create_date        timestamp,
    email              varchar(255),
    iin                varchar(255),
    is_active          varchar(255),
    is_archive         varchar(255),
    is_deleted         boolean,
    is_director        varchar(255),
    legal_entity       boolean,
    is_root            varchar(255),
    name               varchar(255),
    order_file         bytea,
    password           varchar(255),
    patronymic         varchar(255),
    phone_number       varchar(255),
    surname            varchar(255),
    update_date        timestamp,
    deactivated_reason varchar(255),
    first_entry        varchar(255) not null,
    is_deactivated     boolean,
    legal_entity_id    bigint
        constraint fkmq14gb5njhg8g9w5tb0f32pk6
            references legal_entity,
    org_struct_id      bigint
);

create table auth_action_log
(
    id               bigint not null
        primary key,
    action           varchar(255),
    create_date      timestamp,
    last_update_date timestamp,
    module_level_id  bigint,
    name             varchar(255),
    role_id          varchar(255),
    user_id          bigint,
    create_by        bigint
        constraint fkkltosoxm2muutjx3hxx1g85wg
            references auth_user,
    last_update_by   bigint
        constraint fkist5ki0651qocmrj5nh8u4xhf
            references auth_user
);

create table auth_user_dict
(
    access_type varchar(255),
    user_id     bigint not null
        constraint fk2r8tbuehqcq61sw1oqet6h4f0
            references auth_user,
    dict_id     bigint not null
        constraint fkb2fnk045l515n5t3d9o70u5ei
            references auth_dict,
    primary key (dict_id, user_id)
);

create table auth_user_module_level
(
    id              bigint not null
        primary key,
    user_id         bigint
        constraint fkoq5aqhyvnja0hi4ju0yx5cktt
            references auth_user,
    module_level_id bigint
        constraint fkfslhm9fkn2vm6hlgf171jjmj6
            references auth_module_level
);

create table auth_user_role
(
    role    varchar(255) not null
        constraint fkm1wuiwrpf6ckmfqnk56jkwash
            references auth_role,
    user_id bigint       not null
        constraint fkebutsbqm58ehnlffb299ng0ap
            references auth_user,
    primary key (user_id, role)
);

create table notification_template
(
    id               bigint generated by default as identity
        primary key,
    created          timestamp not null,
    created_user_id  bigint,
    is_deleted       boolean,
    modified         timestamp not null,
    modified_user_id bigint,
    code             varchar(255),
    message_kz       varchar(255),
    message_ru       varchar(255),
    subject_kz       varchar(255),
    subject_ru       varchar(255),
    type             varchar(255)
);

create table old_passwords
(
    id          bigint not null
        primary key,
    create_date timestamp,
    hash        varchar(255),
    iin         varchar(255)
);

create table roles
(
    id               bigint generated by default as identity
        primary key,
    created          timestamp not null,
    created_user_id  bigint,
    is_deleted       boolean,
    modified         timestamp not null,
    modified_user_id bigint,
    code             varchar(255),
    name             varchar(255)
);


create sequence ses_id_seq;


create table ses
(
    id       bigint default nextval('ses_id_seq'::regclass) not null
        primary key,
    active   boolean,
    bin      varchar(255),
    dat      timestamp,
    exp_date timestamp,
    iin      varchar(255),
    ip       varchar(255),
    token    varchar,
    user_id  bigint
);

create table status
(
    id        bigint not null
        primary key,
    name_kz   varchar(255),
    name_ru   varchar(255),
    name_tech varchar(255)
);

create table auth_action_role
(
    id              bigint not null
        primary key,
    is_active       varchar(255),
    module_level_id bigint
        constraint fk8ewaa2wvyatu40i491gih7u76
            references auth_module_level,
    action          varchar(255)
        constraint fk5ugqisl0ww0xmgocfjts08hvc
            references auth_action,
    role            varchar(255)
        constraint fk8jgytoixms3yrfw32torx3kso
            references auth_role,
    status_id       bigint
        constraint fketfv0s0ns4a16tf5uqdnqb7uk
            references status
);

create table user_passwords_info
(
    iin                 varchar(255) not null
        primary key,
    last_changed_date   timestamp,
    last_login_date     timestamp,
    valid_login_count   bigint,
    wrong_attempt_count bigint
);


create table user_roles
(
    id               bigint generated by default as identity
        primary key,
    created          timestamp not null,
    created_user_id  bigint,
    is_deleted       boolean,
    modified         timestamp not null,
    modified_user_id bigint,
    role_id          bigint,
    user_id          bigint
);


create table user_session
(
    id          bigint not null
        primary key,
    action      varchar(255),
    active      boolean,
    create_date timestamp,
    details     varchar(255),
    exp_date    timestamp,
    iin         varchar(255),
    ip          varchar(255),
    token       varchar(255)
);


create sequence auth_action_log_id_seq;

create sequence auth_module_level_id_seq;

create sequence auth_user_module_level_s;

create sequence auth_users_s;

create sequence old_passwords_s;

create sequence user_session_s;

create sequence auth_gu_module_level_id_seq;

create sequence user_session_gen
    increment by 50;
