create table if not exists report_puv
(
    id          bigint generated by default as identity,
    full_name  varchar,
    address varchar,
    bin varchar,
    iin varchar,
    requisite varchar,
    device_brand varchar,
    last_verification_date date,
    created_date date,
    create_by varchar,
    deleted_date date,
    deleted_by varchar,
    quarter bigint,
    quarter_date date
);

create table if not exists report_puv_table
(
    id          bigint generated by default as identity,
    report_puv_id bigint,
    object_name varchar,
    long_degree bigint,
    long_min bigint,
    long_sec bigint,
    lat_degree bigint,
    lat_min bigint,
    lat_sec bigint,
    intake_num bigint,
    permit_use bigint,
    established_limit bigint,
    intake_vol_all bigint,
    intake_vol_f bigint,
    intake_vol_s bigint,
    intake_vol_t bigint,
    num_supply_station bigint,
    transfered_users_all bigint,
    transfered_users_mF bigint,
    transfered_users_mS bigint,
    transfered_users_mT bigint,
    ex_loss bigint,
    norm_loss bigint
)
